### ISSUE TITLE
Support for multi-lined description? Hmm

### ISSUE THREAD

**Issue by reeetth** [VictorrPY/Discord-Webhook-Sender#2]
Is that possible in this, if so how do I do it?

**Comment by Victorsitou** [comment]
No, is not possible right now, i'll try to add it, but for now, that is not possible.

**Comment by Victorsitou** [comment]
Hi, sorry for the very late response, but yesterday I decided to rewrite the whole project.

I added multi-line support in [this commit.](https://github.com/Victorsitou/Discord-Webhook-Sender/commit/b9d1dc82e4098586df47b091f100d07c901ecfb0)

To use it, simply add "\n" while you write, this will create another line.
